import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore, doc, getDocFromCache, getDocFromServer } from 'firebase/firestore';

// In a real applet within AI Studio, this file is generated by the set_up_firebase tool.
// We'll wrap it in a try-catch to avoid crashing if it hasn't been set up yet.
import firebaseConfig from '../../firebase-applet-config.json';

const isConfigured = !!firebaseConfig.apiKey && firebaseConfig.apiKey !== "";

if (!isConfigured) {
  console.warn('Firebase API key is missing. Please ensure Firebase is properly set up in AI Studio.');
}

const app = isConfigured ? (getApps().length > 0 ? getApp() : initializeApp(firebaseConfig)) : null;

export const auth = isConfigured ? getAuth(app!) : null as any;
// @ts-ignore
export const db = isConfigured ? getFirestore(app!, firebaseConfig.firestoreDatabaseId) : null as any;

// Connection test as required by instructions
async function testConnection() {
  if (!firebaseConfig.apiKey) return;
  try {
    await getDocFromServer(doc(db, 'test', 'connection'));
  } catch (error) {
    if(error instanceof Error && error.message.includes('the client is offline')) {
      console.error("Please check your Firebase configuration.");
    }
  }
}

if (typeof window !== 'undefined') {
  testConnection();
}
